# Generated by Django 5.1.2 on 2024-10-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Llm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Nome do modelo, ex: gemini-1.5-flash", max_length=100
                    ),
                ),
                (
                    "verbose",
                    models.BooleanField(
                        default=False,
                        help_text="Define se a llm será detalhado nas respostas",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        default=0.5,
                        help_text="Define a temperatura da amostragem",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Papel do agente, ex: 'Content Writer'",
                        max_length=100,
                    ),
                ),
                (
                    "goal",
                    models.TextField(
                        help_text="Objetivo do agente, ex: 'Compose articles on trending topics'"
                    ),
                ),
                (
                    "verbose",
                    models.BooleanField(
                        default=False,
                        help_text="Define se o agente será detalhado nas respostas",
                    ),
                ),
                (
                    "memory",
                    models.BooleanField(
                        default=False,
                        help_text="Se o agente tem ou não memória persistente",
                    ),
                ),
                (
                    "backstory",
                    models.TextField(
                        blank=True, help_text="História de fundo do agente"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        help_text="Modelo de linguagem natural do agente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="crew_api.llm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição da tarefa, incluindo o objetivo e detalhes, ex: 'Compose an insightful article on {topic}'"
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        blank=True,
                        help_text="Formato esperado do output da tarefa, ex: 'A 4 paragraph article on {topic}'",
                    ),
                ),
                (
                    "async_execution",
                    models.BooleanField(
                        default=True,
                        help_text="Define se a execução da tarefa é assíncrona",
                    ),
                ),
                (
                    "output_file",
                    models.CharField(
                        blank=True,
                        help_text="Nome do arquivo de saída para o output da tarefa",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agente responsável pela tarefa",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="crew_api.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("hierarchical", "Hierarchical"),
                        ],
                        help_text="Tipo de processo da equipe",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agents",
                    models.ManyToManyField(
                        help_text="Agentes que compõem a equipe",
                        related_name="crews",
                        to="crew_api.agent",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        help_text="Tarefas atribuídas à equipe",
                        related_name="crews",
                        to="crew_api.task",
                    ),
                ),
            ],
        ),
    ]
