# Generated by Django 5.1.2 on 2024-10-29 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome do agente, ex: 'News Writer'", max_length=100)),
                ('role', models.CharField(help_text="Papel do agente, ex: 'Content Writer'", max_length=100)),
                ('goal', models.TextField(help_text="Objetivo do agente, ex: 'Compose articles on trending topics'")),
                ('verbose', models.BooleanField(default=False, help_text='Define se o agente será detalhado nas respostas')),
                ('memory', models.BooleanField(default=False, help_text='Se o agente tem ou não memória persistente')),
                ('backstory', models.TextField(blank=True, help_text='História de fundo do agente')),
                ('tools', models.JSONField(blank=True, help_text='Ferramentas disponíveis para o agente', null=True)),
                ('llm_model_name', models.CharField(help_text="Nome do modelo de linguagem, ex: 'gemini-1.5-flash'", max_length=50)),
                ('llm_temperature', models.FloatField(default=0.5, help_text='Temperatura do modelo de linguagem')),
                ('llm_verbose', models.BooleanField(default=False, help_text='Modo detalhado para o modelo de linguagem')),
                ('allow_delegation', models.BooleanField(default=False, help_text='Define se o agente pode delegar tarefas a outros agentes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome da tarefa, ex: 'Write Article'", max_length=100)),
                ('description', models.TextField(help_text="Descrição da tarefa, incluindo o objetivo e detalhes, ex: 'Compose an insightful article on {topic}'")),
                ('expected_output', models.TextField(blank=True, help_text="Formato esperado do output da tarefa, ex: 'A 4 paragraph article on {topic}'")),
                ('parameters', models.JSONField(blank=True, help_text='Parâmetros específicos para a execução da tarefa', null=True)),
                ('async_execution', models.BooleanField(default=True, help_text='Define se a execução da tarefa é assíncrona')),
                ('output_file', models.CharField(blank=True, help_text='Nome do arquivo de saída para o output da tarefa', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text='Agente responsável pela tarefa', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crew_api.agent')),
            ],
        ),
    ]
