# Generated by Django 5.1.2 on 2024-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_api', '0002_remove_agent_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.CharField(blank=True, help_text='Nome do arquivo de saída para o output da tarefa', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('sequential', 'Sequential'), ('hierarchical', 'Hierarchical')], help_text='Tipo de processo da equipe', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agents', models.ManyToManyField(help_text='Agentes que compõem a equipe', related_name='crews', to='crew_api.agent')),
                ('tasks', models.ManyToManyField(help_text='Tarefas atribuídas à equipe', related_name='crews', to='crew_api.task')),
            ],
        ),
    ]
